### ISSUE TITLE
怎么让fragment刷新呢

### ISSUE THREAD

**Issue by AnserBaby** [yechaoa/wanandroid_kotlin#1]
我用你这个模板做了个别，但是不知道怎么让fragment每次切换都刷新界面

**Comment by yechaoa** [comment]
可以在onResume里面刷新，或者判断是否可见

**Comment by AnserBaby** [comment]
> 可以在onResume里面刷新，或者判断是否可见

谢谢啊，百度出来的不怎么行，新手不知道怎么弄，只能换成replace了
